# v https://github.com/codecov/example-go

language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

env:
  - CODECOV_TOKEN=742b6ab5-de5b-49e1-943d-e65efa19007a

before_install:
  - go get -t -v ./... && go build -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
